### GET Consulta todos los libros
GET http://localhost:3000/books HTTP/1.1

### END point para consultar por el id del libro
GET http://127.0.0.1:3000/books/2 HTTP/1.1

### Crear el end point para insertar datos al json
POST http://localhost:3000/books HTTP/1.1
Content-Type: application/json

{
    "name": "Caracortada",
    "author": "Diego Villa",
    "year": 2024
}

### Ruta PUT para actualizar un libro existente
PUT http://localhost:3000/books/4 HTTP/1.1
Content-Type: application/json

{
    "year": 2019
}

### Ruta para eliminar un dato por su ID
DELETE http://localhost:3000/books/7 HTTP/1.1
